import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chan Lee Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon-16x16.ico" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
